### ISSUE TITLE
Lazy corners creation for IE

### ISSUE THREAD

**Issue by outring** [sergeche/rocon#3]
При большом количестве элементов, которые надо скруглить, страница будет долго открываться из-за того, что нужно создать очень много элементов. Может сделать чтобы скруглялись только элементы в пределах видимости плюс 100-200 пикселей вверх и вниз? При скроллинге и ресайзе нескруглённые доскруглять

**Comment by sergeche** [comment]
Тут есть две проблемы: нужно получить абсолютные координаты всех блоков (а это тоже время и нагрузка) и не понятно, что делать с блоками, которые сейчас скрыты (`display: none`) но должны появится по скрипту. Думаю, лучше будет сделать неблокирующую интерфейс генерацию уголков

**Comment by outring** [comment]
Неактуально
