### ISSUE TITLE
IE6 1px bug ♦

### ISSUE THREAD

**Issue by outring** [sergeche/rocon#4]
В IE6 как известно нижние уголки могут неплотно прилегать к нижнему краю контейнера. Если подумать, то у нас возможны 3 случая:
1. Высота контейнера не задана. В этом случае нижние уголки нужно делать не абсолютными, а по методу описанному здесь: http://www.pmob.co.uk/temp/onepxgap.htm
2. Высота контейнера задана в px. В этом случае можно расчитать или top для уголка или сделать корректировку для его bottom
3. Высота контейнера задана в относительных единицах. В этом случае всё по старому (или можно проверить заданы ли размеры relative родителя этого блока в px и использовать случай 2)
Итого получается, что в подавляющем большинстве случаев мы получим хорошо выглядящие нижние уголки, т.к. в относительных единицах высота задаётся очень редко

**Comment by sergeche** [comment]
Это всё простейшие случаи для статических страниц. Если подключается JS, который начинает менять размеры блока или добавлять контент. Проблемя с нижними углами в IE6 решена в общем виде, для конкретных случаев понадобится небольшая правка CSS

**Comment by outring** [comment]
Похоже, что это больше не актуально 😅 

_GH выкатил быстрый доступ ко всем PR/Issues, решил почистить_
