### ISSUE TITLE
document.readyState === "complete"

### ISSUE THREAD

**Issue by arestov** [sergeche/rocon#5]
если событие DOMContentLoaded сработало до того как выполнен rocon.js то ничего не будет нарисовано.

для этого достаточно в начало функции  bindReady
 и после

```
if ( readyBound ) return;
readyBound = true;
```

приписать 
    if ( document.readyState === "complete" ) {
        fireReady();
        return
    }

тогда rocon.js можно использовать так jQuery.require('rocon.js') (неблокирующая рендеринг загрузка скриптов)

**Comment by outring** [comment]
Кстати хотелось бы иметь возможность запускать рендеринг по своему эвенту

**Comment by arestov** [comment]
выснилось, что сафари не очень дружит с этим, и вообще там чёто не очень всё)
http://webo.in/articles/habrahabr/05-delayed-loading/
ну да ладно :)
